### ISSUE TITLE
Apply policy on HCL

### ISSUE THREAD

**Issue by samof76** [b4b4r07/stein#10]
## WHAT
I am trying to apply a policy on the HCL file, which looks like the following,

```
test "hello" {
    number = 6
    string = "sample"
}
```
I am unable to come up with the `jsonpath` for the condition to check `number == 6`. 

I Know this is not an issue? But i would better documented.

**Comment by b4b4r07** [comment]
@samof76 

Sorry for the late reply.

This HCL file is equivalent to this JSON:

```json
{
  "test": [
    {
      "hello": [
        {
          "number": 6,
          "string": "sample"
        }
      ]
    }
  ]
}
```

So you can check `number == 6` with the following jsonpath formula.

```hcl
rule "test" {
  description = "test"

  conditions = [
    "${jsonpath("test.0.hello.0.number") == 7}",
  ]

  report {
    level   = "ERROR"
    message = "${format("%d is six, not seven\n", jsonpath("test.0.hello.0.number"))}"
  }
}
```

I know the difficulty of specifying the field in case of HCL, in jsonpath function. I know I have to think about more suitable solution for this.

**Comment by b4b4r07** [comment]
Looks it's done. Feel free to open again if you still have something to ask me.
